---
title: "Tema 1"
output: html_notebook
---
Incarca librarii

```{r warning=FALSE}
library(corrplot)
library("gplots")
library(MASS)
library(e1071)
library(dplyr)
library("plot3D")
```

Reading data

```{r}
train = read.csv("./input/train.csv")
summary(train)
```
Analizam boxploturile

```{r}
boxplot(train$Age,main="Age")
boxplot(train$SibSp,main="Siblings")
boxplot(train$Parch,main="Parch")
boxplot(train$Fare,main="Fare")
```

Analizam histogramele

```{r}
barplot(table(train$Survived),main="Survived")
hist(train$Age,main="Age")
hist(train$SibSp,main="Siblings")
hist(train$Parch,main="Parch")
hist(train$Fare,main="Fare")
barplot(table(train$Pclass),main="Pclass")
barplot(table(train$Sex),main="Sex")
barplot(table(train$Ticket),main="Ticket")
barplot(table(train$Embarked),main="Embarked")
```

Age distribution
```{r}
plot(density(train$Age, na.rm = T), main="Age distribution")
paste("skewness = ", skewness(train$Age, na.rm = T)) 
paste("kurtosis = ", kurtosis(train$Age, na.rm = T)) 

```
SibSp distribution
```{r}
plot(density(train$SibSp, na.rm = T), main="SibSp distribution")
paste("skewness = ", skewness(train$SibSp, na.rm = T)) 
paste("kurtosis = ", kurtosis(train$SibSp, na.rm = T)) 

```
Fare distribution
```{r}
plot(density(train$Fare, na.rm = T), main="Fare distribution",col=iris[,5])
paste("skewness = ", skewness(train$Fare, na.rm = T)) 
paste("kurtosis = ", kurtosis(train$Fare, na.rm = T)) 

```
Parch distribution
```{r}
plot(density(train$Parch, na.rm = T), main="Parch distribution")
paste("skewness = ", skewness(train$Parch, na.rm = T)) 
paste("kurtosis = ", kurtosis(train$Parch, na.rm = T)) 

```



Analiza bivariata
```{r  fig.width=10, fig.height=10}

pairs(train[,c("Sex","Age","Pclass","SibSp","Parch","Ticket","Fare","Embarked")])

 

#library(GGally)
#ggpairs(train, diag=list(continuous="density", discrete="bar"), axisLabels="show")
```
3d Graphics

```{r warning=FALSE}

library("scatterplot3d") # load

data = train[,c("Age","Pclass", "Fare")]

matrix = data.matrix(data)
colors = c("#999999", "#E69F00", "#56B4E9")
colors = colors[as.numeric(train$Pclass)]
s3d = scatterplot3d(matrix[,1:3], pch = 16, color=colors, main = "Classes based on age and fare")
text(s3d$xyz.convert(matrix[, 1:3]), labels = rownames(matrix),
     cex= 0.7, col = "steelblue")

```


Principal components Analysys plots between 2 variables
```{r}
train_aux = train[,c("Sex","Age","Pclass","SibSp","Parch","Fare","Embarked")]
train_aux$Age[is.na(train_aux$Age)] = mean(train$Age, na.rm = T)
train_aux$Sex = as.numeric((as.factor(train_aux$Sex)))
train_aux$Embarked = as.numeric((as.factor(train_aux$Embarked)))
train_aux$Embarked[is.na(train_aux$Embarked)] = 3
pca <- prcomp(train_aux)
summary(pca)
biplot(pca, choices = c(1,2))
plot(pca, type = "l")
pairs(pca$x[, c(1,2)],col=iris[,5])
```

Scatterplots


Calculul corelatiiei dintre variabile

```{r}

df <- train %>% dplyr::select(Age, Sex, Pclass, Fare, Embarked, SibSp, Parch)
df$Age[is.na(df$Age)] <- mean(df$Age,na.rm = T)
df$Sex <- as.numeric(df$Sex)
df$Embarked <- as.numeric(df$Embarked)

corrplot(cor(df), type ='upper', method ='ellipse', tl.pos ='tp')
corrplot(cor(df), type ='lower', method ='number', add = T, col='black', cl.pos='n',diag=F)
```

Testul de independenta

```{r warning=FALSE}
chisq.test(table(train$Age,train$Sex)) 
chisq.test(table(train$Age,train$Embarked)) 
chisq.test(table(train$Age,train$SibSp)) 
chisq.test(table(train$Age,train$Parch)) 
chisq.test(table(train$Sex,train$Embarked))
chisq.test(table(train$Sex,train$SibSp))
chisq.test(table(train$SibSp,train$Parch))

mapply(function(x, y) chisq.test(x, y)$p.value, train[, -5], MoreArgs=list(train[,5]))

```
tsne
```{r}

library(caret)  
library(Rtsne)

tsne_model_1 = Rtsne(as.matrix(train_aux), check_duplicates=FALSE, pca=TRUE, perplexity=30, theta=0.5, dims=2)
d_tsne_1 = as.data.frame(tsne_model_1$Y)
## plotting the results without clustering
ggplot(d_tsne_1, aes(x=V1, y=V2)) +  
  geom_point(size=0.25) +
  guides(colour=guide_legend(override.aes=list(size=6))) +
  xlab("") + ylab("") +
  ggtitle("t-SNE") +
  theme_light(base_size=20) +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank()) +
  scale_colour_brewer(palette = "Set2")
```


Corelatia

```{r}

df2 <- train %>% dplyr::select(Survived, Age, Sex, Pclass, Fare, Embarked, SibSp, Parch)
df2$Age[is.na(df2$Age)] <- mean(df2$Age,na.rm = T)
df2$Sex <- as.numeric(df2$Sex)
df2$Embarked <- as.numeric(df2$Embarked)

corrplot(cor(df2), type ='upper', method ='ellipse', tl.pos ='tp')
corrplot(cor(df2), type ='lower', method ='number', add = T, col='black', cl.pos='n',diag=F)
```

